version: "2.4"
services:
    api:
        image: circascreens/vice-prod-test
        container_name: nodeapp
        hostname: nodeapp.localdomain
        ports:
            - 80:80
            - 3000:3000
            - 443:443
        volumes:
            - /data/media:/data/media
            - ./:/data/project/NodeApp
    db:
        image: couchbase/server:enterprise-5.5.6
        hostname: db
        container_name: db
        restart: always
        volumes: 
            - ./etc:/opt/couchdb/etc/local.d  
            - ./data:/opt/couchdb/data
            - ./log:/opt/couchdb/var/log
        ports:
            - 5984:5984
            - 11210:11210
            - 8091:8091
            - 8092:8092
            - 8093:8093
            - 8094:8094
        
volumes:
    couchdb:
    media:
